[versions]
## Libraries
# Kotlin
kotlinx-serialization = "1.8.0"

# AndroidX
androidx-activity = "1.10.1"
androidx-splashscreen-core = "1.0.1"
androidx-appcompat = "1.7.0"
androidx-datastore-preferences = "1.1.5"
androidx-navigation = "2.8.9"

# Compose
androidx-compose-bom = "2025.04.01"

# DI
google-hilt = "2.55"
google-hilt-navigation-compose = "1.2.0"

# Room
androidx-room = "2.7.1"

# Helpers
accompanist = "0.37.2"

# Paging
androidx-paging = "3.3.6"

# Location
google-location = "21.3.0"

# Maps
osmdroid-maps = "6.1.20"

# Lint
slack-compose-lint = "1.4.2"

# Charts
dev-vico-compose = "2.0.2"

## Plugins
agp = "8.9.2"
kotlin = "2.1.10"
# hilt plugin has same version as hilt library so it is declared in the library section
ksp = "2.1.10-1.0.29"

[libraries]
# Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# AndroidX
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-splashscreen-core = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashscreen-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences-android", version.ref = "androidx-datastore-preferences" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-compose-material3-window-sizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# DI
google-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-hilt" }
google-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-hilt" }
google-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "google-hilt-navigation-compose" }

# Room
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }

# Helpers
google-accompanist = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# Paging
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }

# Location
google-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "google-location" }

# Maps
osmdroid-android = { group = "org.osmdroid", name = "osmdroid-android", version.ref = "osmdroid-maps" }
osmdroid-mapsforge = { group = "org.osmdroid", name = "osmdroid-mapsforge", version.ref = "osmdroid-maps" }

# Lint
slack-compose-lint = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "slack-compose-lint" }

# Charts
dev-vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "dev-vico-compose" }
dev-vico-compose-material3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "dev-vico-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
